# This workflow runs code quality checks and tests
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install dependencies
      run: uv sync --dev --extra pydantic
      
    - name: Run ruff linting
      run: uv run ruff check cocapi
      
    - name: Run ruff formatting check
      run: uv run ruff format --check cocapi
      
    - name: Run mypy type checking
      run: uv run mypy cocapi
      
    - name: Run tests  
      run: uv run pytest tests/test_cocapi.py -v --tb=short