# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: isort

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  isort:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sort imports
      run: |
        isort cocapi
